[project]
name = "keepiss"
version = "0.1.0"
description = "not emacs, not vim. just an editor"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pyfiglet>=1.0.4",
    "ruff>=0.15.15",
    "textual[syntax]>=8.2.7",
]

[tool.uv.workspace]
members = [
    "trash/TerMan",
    "trash/TermEdit",
]
